---
# tasks file for ansible-role-slurm

- name: Add all the slurm hosts to /etc/hosts
  when:
    - slurm_update_etc_hosts_file | bool
    - not '"docker" in virtualization_tech_guest'  # We cannot modify /etc/hosts in container
  block:

    - name: Add slurm master to /etc/hosts
      ansible.builtin.blockinfile:
        dest: /etc/hosts
        marker_begin: "BEGIN slurm master host"
        marker_end: "END slurm master host"
        block: |
          {{ hostvars[slurm_master_host]['ansible_default_ipv4']['address'] }}  {{ slurm_master_host }}

    - name: Add slurmdbd to /etc/hosts
      ansible.builtin.blockinfile:
        dest: /etc/hosts
        marker_begin: "BEGIN slurm dbd host"
        marker_end: "END slurm dbd host"
        block: |
          {{ hostvars[slurm_dbd_host]['ansible_default_ipv4']['address'] }}  {{ slurm_dbd_host }}

    - name: Add all the worker nodes to /etc/hosts
      ansible.builtin.blockinfile:
        dest: /etc/hosts
        marker_begin: "BEGIN slurm workers hosts"
        marker_end: "END slurm workers hosts"
        block: |
          {% for node in groups[slurm_workers_group]  %}
          {{ hostvars[node]['ansible_default_ipv4']['address'] }}  {{ node }}
          {% endfor %}

    - name: Add all the submit nodes to /etc/hosts
      ansible.builtin.blockinfile:
        dest: /etc/hosts
        marker_begin: "BEGIN slurm submit hosts"
        marker_end: "END slurm submit hosts"
        block: |
          {% for node in groups[slurm_submit_group]  %}
          {{ hostvars[node]['ansible_default_ipv4']['address'] }}  {{ node }}
          {% endfor %}


- name: Update apt cache on Debian/Ubuntu systems
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 600
  when:
    - ansible_os_family == 'Debian'
    - slurm_update_apt_cache
  changed_when: false

- name: Download slurm config from git if "slurm_config_git_repo" is defined
  when: slurm_config_git_repo is defined
  block:

    - name: Install git
      ansible.builtin.package:
        name: git
        state: present

    - name: Copy github-service-user key
      ansible.builtin.copy:
        content: "{{ slurm_github_identity }}"
        dest: /root/.ssh/slurm_github_ed25519
        owner: root
        group: root
        mode: '0400'
      when: slurm_github_identity | length > 0

    - name: Add github-service-user in the ssh configuration
      community.general.ssh_config:
        user: root
        remote_user: git
        host: "github.com-slurm-config"
        hostname: "github.com"
        identity_file: "/root/.ssh/slurm_github_ed25519"
        state: present
      when: slurm_github_identity | length > 0

    - name: Add github servers to known hosts
      ansible.builtin.known_hosts:
        name: github.com
        key: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
        path: /root/.ssh/known_hosts
        state: present
      when: slurm_github_identity | length > 0

    - name: Deploy slurm config file from a git repo
      ansible.builtin.git:
        repo: "{{ slurm_config_git_repo }}"
        dest: /etc/slurm/
        version: "{{ inventory_dir | basename }}"
        force: true
      notify: Restart slurm services
      environment:
        GIT_SSL_NO_VERIFY: "True"

- name: Install EPEL repository
  ansible.builtin.yum:
    name: epel-release
    state: installed
  when:
    - slurm_add_epel_repo | bool
    - ansible_os_family == "RedHat"

- name: Install OpenHPC repositories (RHEL7)
  ansible.builtin.yum:
    name: "{{ slurm_ohpc_repos_url['rhel7'] }}"
    state: installed
  when:
    - slurm_add_openhpc_repo | bool
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Install OpenHPC repositories (RHEL8)
  ansible.builtin.yum:
    name: "{{ slurm_ohpc_repos_url['rhel8'] }}"
    state: installed
    disable_gpg_check: true
  when:
    - slurm_add_openhpc_repo | bool
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: Install common Slurm packages
  ansible.builtin.package:
    name: "{{ slurm_packages_common[ansible_os_family] }}"
    state: present
  tags: munge

- name: Generate a Munge key for the cluster in the slurm-master host
  ansible.builtin.command: "dd if=/dev/urandom of=/etc/munge/munge.key bs=1 count=1024"
  args:
    creates: /etc/munge/munge.key
  delegate_to: "{{ slurm_master_host }}"
  notify: Restart munge service
  no_log: true
  tags: munge

- name: Set permissions for /etc/munge/munge.key in master
  ansible.builtin.file:
    path: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400
  delegate_to: "{{ slurm_master_host }}"
  tags: munge

- name: Retrieve Munge key from slurm-master host
  ansible.builtin.slurp:
    src: "/etc/munge/munge.key"
  register: _slurm_munge_key
  delegate_to: "{{ slurm_master_host }}"
  no_log: true
  tags: munge

- name: Write Munge key to every host in the cluster
  ansible.builtin.copy:
    content: "{{ _slurm_munge_key.content | b64decode }}"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: 0400
  when: ("slurm_dbd_host in inventory_hostname") or
        ("slurm_workers_group in group_names") or
        ("slurm_submit_group in group_names")
  notify: Restart munge service
  no_log: true
  tags: munge

- name: Start and enable munge service
  ansible.builtin.service:
    name: munge
    state: started
    enabled: true
  tags: munge

- name: Configure slurm accounting daemon
  ansible.builtin.include_tasks: slurm-accounting.yml
  when: "slurm_dbd_host in inventory_hostname"

- name: Configure slurm master daemon
  ansible.builtin.include_tasks: slurm-master.yml
  when: "slurm_master_host in inventory_hostname"

- name: Configure slurm workers
  ansible.builtin.include_tasks: slurm-worker.yml
  when: "slurm_workers_group in group_names"

- name: Configure slurm submit hosts
  ansible.builtin.include_tasks: slurm-submit.yml
  when:
    - "slurm_submit_group in group_names"
    - "not slurm_workers_group in group_names"
