---

- name: Install slurm master packages
  ansible.builtin.package:
    name: "{{ slurm_packages_master[ansible_os_family] }}"
    state: present

- name: Deploy /etc/slurm/job_submit.lua
  ansible.builtin.template:
    dest: /etc/slurm/job_submit.lua
    src: job_submit.lua.j2
    owner: root
    group: root
    mode: 0755
  when:
    - slurm_config_deploy_lua_submit_plugin
    - not slurm_config_git_repo is defined

- name: Start and enable slurm master daemon
  ansible.builtin.service:
    name: slurmctld
    state: started
    enabled: true
