---

- name: RedHat | Create the python venv to install OpenStack client on RedHat systems
  block:

    - name: RedHat | Install python3 and virtualenv from EPEL
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
          - python3-virtualenv
        state: installed

    - name: RedHat | Install python2-setuptools required by the ansible pip module
      ansible.builtin.yum:
        name: python-setuptools
        state: installed

    - name: RedHat | Create python virtualenv to install the openstack client
      ansible.builtin.pip:
        name:
          - setuptools>46.1.3
          - pip>20.0.2
          - python-openstackclient
        virtualenv: "{{ slurm_openstack_venv_path }}"
        virtualenv_command: virtualenv-3

  when: ansible_os_family == "RedHat"


- name: Debian/Ubuntu | Create the python venv to install OpenStack client on Debian/Ubuntu systems
  block:

    - name: Debian/Ubuntu | Install virtualenv
      ansible.builtin.apt:
        name: python3-virtualenv
        state: present

    - name: Debian/Ubuntu | Create python virtualenv to install the openstack client
      ansible.builtin.pip:
        name:
          - setuptools>46.1.3
          - pip>20.0.2
          - python-openstackclient
        virtualenv: "{{ slurm_openstack_venv_path }}"
        virtualenv_command: virtualenv

  when: ansible_os_family == "Debian"

- name: Deploy /etc/slurm/slurm_resume_openstack.py
  ansible.builtin.template:
    src: slurm_resume_openstack.py.j2
    dest: /etc/slurm/slurm_resume_openstack.py
    owner: "{{ slurm_user[ansible_os_family] }}"
    group: "{{ slurm_group[ansible_os_family] }}"
    mode: 0755

- name: Deploy /etc/slurm/slurm_suspend_openstack.py
  ansible.builtin.template:
    src: slurm_suspend_openstack.py.j2
    dest: /etc/slurm/slurm_suspend_openstack.py
    owner: "{{ slurm_user[ansible_os_family] }}"
    group: "{{ slurm_group[ansible_os_family] }}"
    mode: 0755

- name: Create folder /etc/openstack/ to deploy /etc/openstack/clouds.yaml
  ansible.builtin.file:
    path: /etc/openstack/
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Deploy /etc/openstack/clouds.yaml
  ansible.builtin.template:
    src: clouds.yaml.j2
    dest: /etc/openstack/clouds.yaml
    owner: "{{ slurm_user[ansible_os_family] }}"
    group: "{{ slurm_group[ansible_os_family] }}"
    mode: 0700
