---

- name: Install cgroups if this is a worker host | RedHat
  ansible.builtin.yum:
    name:
      - libcgroup
      - libcgroup-tools
    state: present
  when: ansible_os_family == "RedHat"

- name: Install cgroups if this is a worker host | Debian
  ansible.builtin.apt:
    name:
      - libcgroup1
      - cgroup-tools
    state: present
  when: ansible_os_family == "Debian"

- name: Deploy /etc/slurm/cgroup.conf
  ansible.builtin.template:
    src: "{{ slurm_conf_cgroup_custom_template | default('cgroup.conf.j2') }}"
    dest: /etc/slurm/cgroup.conf
    owner: root
    group: root
    mode: 0644
  when: not slurm_config_git_repo is defined
  notify: restart slurm services

- name: Enable and start cgroup services if this is a worker_node
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  when:
    - not ansible_virtualization_type == "docker"
    - not ansible_virtualization_type == "containerd"
  with_items:
    - cgred
    - cgconfig

- name: Install slurm worker packages
  ansible.builtin.package:
    name: "{{ slurm_packages_worker[ansible_os_family] }}"
    state: present

- name: Ensure the slurmd spool directory exists
  ansible.builtin.file:
    path: "{{ slurm_slurmd_spool_path | default('/var/spool/slurmd') }}"
    owner: "{{ slurm_user[ansible_os_family] }}"
    group: "{{ slurm_group[ansible_os_family] }}"
    mode: 0755
    state: directory

- name: Make a symlink /var/log/slurm >> /var/log/slurm-llnl on Debian based systems
  file:
    src: /var/log/slurm-llnl
    dest: /var/log/slurm
    owner: root
    group: root
    state: link
  when: ansible_os_family == "Debian"

- name: Start and enable slurm worker daemon
  ansible.builtin.service:
    name: slurmd
    state: started
    enabled: true
