---

- name: Install cgroups if this is a worker host | RedHat
  ansible.builtin.yum:
    name:
      - libcgroup
      - libcgroup-tools
    state: present
  when: ansible_os_family == "RedHat"

- name: Install cgroups if this is a worker host | Debian
  ansible.builtin.apt:
    name:
      - libcgroup1
      - cgroup-tools
    state: present
  when: ansible_os_family == "Debian"

- name: Deploy /etc/slurm/cgroup.conf
  ansible.builtin.template:
    dest: /etc/slurm/cgroup.conf
    src: cgroup.conf.j2
    owner: root
    group: root
    mode: 0644
  notify: restart slurm services

- name: Enable and start cgroup services if this is a worker_node
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  when:
    - not ansible_virtualization_type == "docker"
    - not ansible_virtualization_type == "containerd"
  with_items:
    - cgred
    - cgconfig

- name: Install slurm worker packages
  ansible.builtin.package:
    name: "{{ slurm_packages_worker[ansible_os_family] }}"
    state: installed

- name: Start and enable slurm worker daemon
  ansible.builtin.service:
    name: slurmd
    state: started
    enabled: true
