---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: List clusters registered in the accounting db
      ansible.builtin.shell: |
        set -o pipefail
        sacctmgr list cluster --noheader --parsable | wc -l
      args:
        executable: /bin/bash
      register: _sacctmgr_output_verify

    - name: Verify the cluster is registered in accounting db
      ansible.builtin.assert:
        that:
          - _sacctmgr_output_verify.stdout == "1"

    - name: List slurm workers
      ansible.builtin.shell: |
        set -o pipefail
        sinfo | wc -l
      args:
        executable: /bin/bash
      register: _sinfo_output_verify

    - name: Verify sinfo can see a compute node
      ansible.builtin.assert:
        that:
          - _sinfo_output_verify.stdout == "2"
