name: publish new releases to ansible galaxy

on:
  release:
    types:
      - published

  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  release:
    needs:
      - lint
      - molecule
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
